### ISSUE TITLE
Combat Tracker Refresh

### ISSUE THREAD

**Issue by TheHassi** [MalphasDev/darkspace_foundryVTT#1]
Wenn man am Anfang des Kampfes das Fenster neu lädt, werden die Initiativen nicht mehr richtig übernommen.

**Comment by MalphasDev** [comment]
Muss vorerst in die Liste "Bekannter Probleme / Known issues" aufgenommen werden, da ich zur Zeit auf eine veraltete Methode zurückgreife ( Combat.updateCombatants() ) und die, zu bevorzugende Methode Combatant.update() nur den aktuellen Combatant updated und nicht die Combatant-ID zur identifikation benutzt.

**Comment by MalphasDev** [comment]
Nach Überarbeitung der CombatTrackers.js und Combat.js scheint dieser Bug behoben. 
Weitere Tests sind notwendig.

**Comment by MalphasDev** [comment]
Tests mit dem aktuellen Combat Tracker haben keine Inkonsistenzen gefunden.
