### ISSUE TITLE
Ausgeklappter Combat-Tracker funktioniert nicht

### ISSUE THREAD

**Issue by TheHassi** [MalphasDev/darkspace_foundryVTT#13]
- die AE werden nicht ordentlich angezeigt und aktualisiert

**Comment by MalphasDev** [comment]
Wurde behoben. Manipulation der des innerHTML wurde ersetzt durch Anzeigen der AE-Kosten-Variable mittels Handlebars und dem aktuallieren des Trackers per render()-Methode.
