### ISSUE TITLE
Combat Tracker: Ersetze oder ergänze die Uhr, Bedienreihenfolge

### ISSUE THREAD

**Issue by runeb68** [MalphasDev/darkspace_foundryVTT#15]
... und/oder ändere die Reihenfolge.

Die Uhr ist da wo man den Submit / Bestätigungsknopf nach Bedienen des Sliders oder der Knopf erwarten wurde. Stattdessen muß man oben drüber auf die aktuelle Summe klicken. Diese sollte direkt unter dem Slider (Schieberegler) oder Knöpfen sein. Intuitive Formulare füllt man grundsätzlich von oben nach unten aus...

Ich würde hinter der Uhr einen Text wie "Abwarten" schreiben. Sie darf gerne zuunterst stehen bleiben.
Vielleicht könnte man der AE Ausgeben Zeile auch ein Symbol voranstellen wie einen grünen Haken.

**Comment by MalphasDev** [comment]
> Intuitive Formulare füllt man grundsätzlich von oben nach unten aus
Genau darum ist die Uhr unter dem Absenden-Button. "Warten" ist eine gesonderte Aktion, die den Charakter aus der Initiativ-Reihenfolge wirft. Versehentlichen anklicken kann zu Verzögerung des Spielflusses führen. 

> Ich würde hinter der Uhr einen Text wie "Abwarten" schreiben.
Wurde vor zwei Versionen eingefügt.

> Vielleicht könnte man der AE Ausgeben Zeile auch ein Symbol voranstellen wie einen grünen Haken.
Es wurde ein ">>" als Symbol eingefügt. Allerdings will ich auf farbliche Hervorhebung verzichten.
