### ISSUE TITLE
Combat Tracker AE ausgegeben

### ISSUE THREAD

**Issue by TheHassi** [MalphasDev/darkspace_foundryVTT#2]
Wenn man mit den Buttons oder Labels die AE ausgegeben: 1AE  ändern möchte:

Error auf Console:

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
(anonymous) @ foundry.js:4889

**Comment by MalphasDev** [comment]
Nach aktuellem Wissensstand durch das Löschen von event.preventDefault() in der _increaseAE() Methode behoben.
