### ISSUE TITLE
EP Tracker

### ISSUE THREAD

**Issue by MalphasDev** [MalphasDev/darkspace_foundryVTT#24]
EP-Tracker:
1: Main-Tracker: Gesamtwert aller Attribute und Fertigkeiten
1.1: Attributstracker: Tracker, der den Wert einzelner Attribute und Fertigkeiten misst. Könnte im Feld für das Löschen von Eigenschaften untergebracht werden.
2: Punkte-Tracker: Gesamtwert aller gekauften Punkte (Anomalie, Netzwerk, Ressourcen)

**Comment by SpiritSparkDev** [comment]
Aktueller EP Tracker zeigt EP falsch an: Eigenschaften und Artifizierungen müssen neu eingebunden werden.

**Comment by SpiritSparkDev** [comment]
EP-Counter gefixted.
