### ISSUE TITLE
Minus - Slider - Plus

### ISSUE THREAD

**Issue by TheHassi** [MalphasDev/darkspace_foundryVTT#4]
Vor jedem Slider ein Minus und nach dem Slider einen Plus.

Damit man für kleine Änderung einfach einen Klick machen kann und nur hin und her gehen muss, weil man zu weit ging.

**Comment by MalphasDev** [comment]
Slider-Buttons für Attribut-Ressourcen (Anomalie, Ressourcen, Bekanntheit, Traumapunkte) hinzufügt. Außerdem dieselben Buttons für Betäubungen und Verletzungen eingefügt.
