### ISSUE TITLE
Item GM: -2 Mittelgroß

### ISSUE THREAD

**Issue by TheHassi** [MalphasDev/darkspace_foundryVTT#5]
Wenn man -2 in dem GM Feld eingibt, ändert sich der Text erfolgreich zu mittelgroß, aber dieser wird dann unter die TextBox verschoben. Bei allen anderen Werten steht der Text links daneben

**Comment by MalphasDev** [comment]
Generell behoben. Zuständiges Grid wurde verändert. Bei zu schmalen Fenster tritt der Fehler jedoch wieder auf.
