### ISSUE TITLE
Charakter Fenster Pop-Up

### ISSUE THREAD

**Issue by TheHassi** [MalphasDev/darkspace_foundryVTT#6]
Es wäre gut, wenn man das Charakterfenster als Pop-Up aufmachen kann.

Variante 1:  Wie bei D&D im Charakterblatt
Variante 2:  Mit Rechtsklickt auf dem Charakterblatt

**Comment by MalphasDev** [comment]
Wird durch Pop-Out-Module. Eine System-Spezifische Lösung ist nicht geplant.
