### ISSUE TITLE
Würfelwurf einfärben

### ISSUE THREAD

**Issue by TheHassi** [MalphasDev/darkspace_foundryVTT#7]
Man könnte die 9 und die 10 bei den Würfeln einfärben, somit kann man schneller sehen, wie nah man am Krit war.

Zusätzlich: 
könnte man die 10 extra einfärben, da diese ja explodiert.

super zusätzlich:
man könnte den Würfel einfärben, welcher durch die Würfelexplosion entstanden ist

**Comment by MalphasDev** [comment]
> man könnte den Würfel einfärben, welcher durch die Würfelexplosion entstanden ist
Meines Wissens kann die Foundry API nicht nachverfolgen, welche Würfel durch einen exploding dice zustande gekommen sind.
